trecapps.falsehoods.self-review=true


# Set up Mongo Repository for Account storage
trecauth.account.repo.strategy=mongo-uri

trecauth.mongo.account.uri=${MONGO_URI}
trecauth.mongo.account.database=tc-accounts


# Establish how to get the keys for JWT Auth token signing and validation
trecauth.jwt.key-storage.strategy=AKV-cred
trecauth.jwt.strategy=RSA

trec.jwt.vault-name=trecappstestvault
trecauth.jwt.rsa.pubic-key-name=trec-2022-pub
trecauth.jwt.rsa.private-key-name=trec-2022-priv-v8

trec.jwt.tenantId=${KV_TENANT}
trec.jwt.clientId=${KV_CLIENT_ID}
trec.jwt.clientSecret=${KV_CLIENT_SECRET}

trecauth.refresh.domain=trecapps.com

trecapps.mongo.falsehoods.uri=${MONGO_URI}
trecapps.mongo.falsehoods.database=tc-falsehoods

# Image and content storage
trecapps.storage.create-strategy=accountAuth
trecapps.storage.account-name=${STORAGE_ACCOUNT_NAME}
trecapps.storage.account-key=${STORAGE_ACCOUNT_KEY}
trecapps.storage.blob-endpoint=${STORAGE_ACCOUNT_ENDPOINT}
trecapps.thumbnail.fallback=/images/Falsehood-icon-Desktop.png

# backend Service URLs

trecapps.image.url=https://test.trecapps.com/Image-man-api
trecapps.falsehoods.url=https://test.trecapps.com/falsehoods
trecapps.login.url=https://test.trecapps.com/User-api
trecapps.falsehoods.base-path=/falsehoods/

# For Field Encryption
trecauth.encryption.strategy=RSA
trecauth.encrypt.rsa.pubic-key-name=tc-field-pub
trecauth.encrypt.rsa.public-key-name=tc-field-pub
trecauth.encrypt.rsa.private-key-name=tc-field-priv

trecauth.encryptor.key-storage.strategy=AKV-cred
trec.encryptor.vault-name=trecappstestvault
trec.encryptor.tenantId=${KV_TENANT}
trec.encryptor.clientId=${KV_CLIENT_ID}
trec.encryptor.clientSecret=${KV_CLIENT_SECRET}