#Scheduling for Key Rotation
trecauth.rotate.do-rotate=true
trecauth.rotate.rotate-cron-schedule=0 0 2 ? * SUN *
trecauth.key.version-count=2

trecauth.refresh.cookie-name=TC_REFRESH
trecauth.request.cookie-name=TC_REQUEST

spring.main.web-application-type=reactive

trecapps.falsehoods.repo.strategy=mongo-uri